version: 2

jobs:
  build:
    docker:
      - image: dideler/fish-shell:3.0.2
    shell: fish
    steps:
      - checkout
      - run:
          name: Install curl + python + ffmpeg
          command: |
            apt-get update --quiet
            apt-get install --yes --quiet curl python ffmpeg
      - run:
          name: Install youtube-dl
          command: |
            curl -sL https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            chmod a+rx /usr/local/bin/youtube-dl
            youtube-dl --version
      - run:
          name: Install fisher
          command: |
            curl -sLo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
            fisher --version
      - run:
          name: Install fish-dl
          command: |
            fisher add < fishfile
            fisher add (pwd)
      - run:
          name: Run tests
          command: fishtape test/*.fish
