version: 2

jobs:
  build:
    docker:
      - image: dideler/fish-shell:3.2.2
    shell: fish
    steps:
      - checkout
      - run:
          name: Install curl + python + ffmpeg + ruby
          command: |
            apt-get update --quiet
            apt-get install --yes --quiet curl python ffmpeg ruby
      - run:
          name: Install youtube-dl
          command: |
            curl -sL https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            chmod a+rx /usr/local/bin/youtube-dl
            youtube-dl --version
      - run:
          name: Install fisher
          command: |
            curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
            fisher --version
      - run:
          name: Install fish-dl
          command: |
            fisher install < fish_plugins
            fisher install .
      - run:
          name: Set XDG cache directory for fish-spin depedency
          command: set -U XDG_CACHE_HOME $HOME/.cache && mkdir -p $XDG_CACHE_HOME
      - run:
          name: Run tests
          command: fishtape test/*.fish
          environment:
            TERM: xterm-256color
